apiVersion: v1
kind: Service
metadata:
  name: {{ include "trcs.fullname" . }}
  labels:
    {{- include "trcs.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "trcs.selectorLabels" . | nindent 4 }}
  ports:
    - name: https
      port: {{ .Values.service.port }}
      targetPort: 8443
      protocol: TCP
      {{- if and .Values.service.nodePort (ne .Values.service.type "ClusterIP") }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
