#!/usr/bin/env bash
set -euo pipefail
cd "$(dirname "$0")/.."
# Usage: hack/gen-kustomize.sh [OUTPUT_DIR [VALUES_FILE...]]
#
# Renders the Helm chart into a plain-YAML Kustomize base. Helm is the single
# source of truth: nothing under a generated directory is edited by hand, and CI
# fails if a committed base differs from a fresh render (make kustomize-check).
# With no arguments it regenerates every base committed in this repository.
# Kustomize users: render a base for YOUR values, then layer overlays on it:
#   hack/gen-kustomize.sh my-base kustomize/helm-values-for-base.yaml my-values.yaml
if [[ $# -eq 0 ]]; then
  "$0" kustomize/base kustomize/helm-values-for-base.yaml
  "$0" kustomize/coco-snp kustomize/helm-values-for-base.yaml examples/values-coco-snp.yaml
  "$0" kustomize/coco-tdx kustomize/helm-values-for-base.yaml examples/values-coco-tdx.yaml
  exit 0
fi
output=$1
shift
if [[ $# -eq 0 ]]; then
  set -- kustomize/helm-values-for-base.yaml
fi
values=()
for file in "$@"; do values+=(-f "$file"); done
tmp=$(mktemp -d)
trap 'rm -rf "$tmp"' EXIT
helm template trcs charts/confidential-inference --skip-tests "${values[@]}" > "$tmp/rendered.yaml"
yq -o=json -I0 '.' "$tmp/rendered.yaml" > "$tmp/documents.json"
python3 - "$tmp/documents.json" "$output" <<'PY'
import json
import pathlib
import subprocess
import sys

source, target = pathlib.Path(sys.argv[1]), pathlib.Path(sys.argv[2])
target.mkdir(parents=True, exist_ok=True)
header = "# Generated by hack/gen-kustomize.sh; do not edit.\n"
for old in target.glob("*.yaml"):
    if not old.read_text().startswith(header):
        raise SystemExit(f"refusing to overwrite non-generated file: {old}")
    old.unlink()
names = []
for line in source.read_text().splitlines():
    document = json.loads(line)
    if not document:
        continue
    name = document["kind"].lower() + "-" + document["metadata"]["name"] + ".yaml"
    if name in names:
        raise SystemExit("duplicate generated resource filename")
    yaml = subprocess.check_output(["yq", "-P", "."], input=json.dumps(document).encode()).decode()
    (target / name).write_text(header + yaml)
    names.append(name)
(target / "kustomization.yaml").write_text(header +
    "apiVersion: kustomize.config.k8s.io/v1beta1\nkind: Kustomization\nresources:\n" +
    "".join("  - " + name + "\n" for name in sorted(names)))
PY
